### ISSUE TITLE
Breaking Dired's i key "dired-maybe-insert-subtree"

### ISSUE THREAD

**Issue by vindarel** [emacsorphanage/emacs-dired-k#38]
Hi !
Looks like dired-k is disturbing the default =i= key, mapped to `dired-maybe-insert-subtree`. With dired-k enable, when I press `i`, the cursor goes to the end of the buffer but it doesn't insert the subtree.  Also, the operation isn't immediate, looks like dired-k makes my cpu work very hard.
Did you experience something similar ?
Without dired-k loaded, all is as usual.

ps: I got it working once after at least 5 tries, weird.

**Comment by syohex** [comment]
Sorry too late response.
I cannot reproduce this issue.

Could you show me how to reproduce your issue with minimum configuration  and tell me your enviroment ?
- Platform
- dired configuration
- dired-k configuration
- etc

**Comment by syohex** [comment]
This package is no longer maintained.
