### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by rgrinberg** [emacsorphanage/emacs-dired-k#42]
dired-k is extremely slow for me on even medium sized buffers (~500 files). Looking at the profiler, it looks like the bottleneck is those `dired-move-to-filename` calls via `dired-next-line` and `dired-get-filename`. It would be great to speed this up somehow. Perhaps by avoiding calling these functions.

**Comment by CyberShadow** [comment]
What's interesting is that even if you colorize (invoke `dired-k`) a dired buffer, merely reverting it (pressing `g`) becomes extremely slow, too. All the added properties added by `dired-k` seem to be slowing `dired` itself down, which seems to spend lots of time invoking `decode-coding-region` and `set-text-property`.

**Comment by CyberShadow** [comment]
My current solution:

```elisp
(defun cs/async-dired-k ()
  "Async wrapper." (when (< (buffer-size) 10000) (run-at-time 0 nil 'dired-k)))
(defun cs/async-dired-k-no-revert ()
  "Async wrapper." (when (< (buffer-size) 10000) (run-at-time 0 nil 'dired-k-no-revert)))
(add-hook 'dired-initial-position-hook 'cs/async-dired-k)
(add-hook 'dired-after-readin-hook #'cs/async-dired-k-no-revert)
```

**Comment by syohex** [comment]
There is no way for resolving this issue. And this package is no longer maintained.
