### ISSUE TITLE
dired-k kills git processes before they can release index.lock

### ISSUE THREAD

**Issue by CyberShadow** [emacsorphanage/emacs-dired-k#45]
For a while now, I've been seeing these errors occur regularly (a few times per day) when I do git operations:

```
fatal: Unable to create '/home/vladimir/.emacs.d/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

It was getting extremely annoying having to delete that file several times per day, and I could not figure out what was causing it, until I set up a `inotifywait` + `notify-send` loop to monitor the creation of the file.

Today I finally discovered the source of the problem: it was `dired-k`. The package will kill git subprocesses before they can release the lock file, which causes it to linger and future operations to fail.

This can be easily reproduced by invoking `dired-k` in quick succession (e.g. `M-x (progn (dired-k) (dired-k))`) in a versioned directory.

Since I was happy with getting file status information via `magit` and `diff-hl`, I stubbed out `dired-k`'s git functionality with:

```elisp
(defun dired-k--inside-git-repository-p () "Override!" nil)
```

**Comment by tarsius** [comment]
> until I set up a inotifywait + notify-send loop to monitor the creation of the file.

Could you post instructions on how to do that please?

**Comment by CyberShadow** [comment]
Sure:
```bash
while true
do
	inotifywait ~/.emacs.d/.git
	sleep 0.1
	if [[ -f ~/.emacs.d/.git/index.lock ]]
	then
		notify-send "index locked"
	fi
done
```

To clarify, it's not necessary to reproduce this issue, only to find the cause of one exhibiting the same symptoms.

**Comment by tarsius** [comment]
Thanks! I was asking because of https://github.com/magit/magit/issues/2708.

**Comment by amosbird** [comment]
@CyberShadow can you try this https://github.com/syohex/emacs-dired-k/pull/46 ?

**Comment by tarsius** [comment]
@syohex Please merge the proposed fix. This causes issues for Magit.

**Comment by notmgsk** [comment]
@syohex ping
